try:
    #2 / 0
    raise RuntimeError("Erro customizado") 
except(ZeroDivisionError):
    print("Divis√£o por zero")
except RuntimeError as e:
    print(str(e))
except:
    print("erro")
finally:
    print("acontece mesmo com erro")